### ISSUE TITLE
MacOS installation guidelines

### ISSUE THREAD

**Issue by lewixlabs** [dracula/arduino-pro-ide#1]
Nice project, thanks!
Could you insert MacOS guidelines?
If you agree, I can make a pull request.

Hi!
Lewix

**Comment by gabrielcaussi** [comment]
Hello lewixlabs, thank you for your interest in collaborating with the theme. I didn't add the guide for MacOS because I don't have one for testing. If you want to make a Pull Request feel free, Ok? I believe it is the same as installing on Linux.

**Comment by lewixlabs** [comment]
Hi @gabrielcaussi 
in MacOS path is similar:
`/Applications/Arduino Pro IDE.app/Contents/Resources/app/plugins/themes`
In this path I added dracula.json file and I restarted Arduino Pro.
Last I pressed CMD+K and CMD+T to select dracula theme.

Thanks!
Lewix

**Comment by gabrielcaussi** [comment]
Hi lewixlabs!

I just added the information you gave me to install on MacOS to the repository.

Could you check to see if this is it?

Link: https://github.com/dracula/arduino-pro-ide/blob/master/INSTALL.md

Thanks!

**Comment by lewixlabs** [comment]
> Hi lewixlabs!
> 
> I just added the information you gave me to install on MacOS to the repository.
> 
> Could you check to see if this is it?
> 
> Link: https://github.com/dracula/arduino-pro-ide/blob/master/INSTALL.md
> 
> Thanks!

Yes, thank you @gabrielcaussi !
Lewix
