### ISSUE TITLE
Please adjust the cursor color

### ISSUE THREAD

**Issue by llkhs** [dracula/arduino-pro-ide#4]
Now the color of the cursor is still black. With the Dracula theme, it is difficult for my eyes to find where the cursor is. Please modify the color of the cursor. Say the name of the field with the cursor color, thank you.
![image](https://user-images.githubusercontent.com/51050409/133088048-21651b65-da5f-48e2-9224-cd645da60ef8.png)

**Comment by gabrielcaussi** [comment]
Thanks for the warning @llkhs!!!

I set the cursor color to white with the VS Code theme. If possible, provide feedback on the functioning.
